homework 3
nfrnl/2020-2-Atom-QA-Python-D-Orlov pull request #3
Opened 2020-10-19 13:33 UTC by nfrnl

# Домашнее задание №3

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
* Написан клиент для API myTarget с возможностью авторизации
* Реализованы тесты на создание и удаление сегментов через API при помощи данного клиента

2020-10-25 13:35 UTC, snicks92 requested changes
Все хорошо, давай удалим лишнее

2020-10-25 13:35 UTC, snicks92 commented on homework_3/api/client.py
> +                raise RequestErrorException(f'Request "{url}" failed with error "{error}"!')
кажется этого не должно быть тут

2020-10-25 16:10 UTC, nfrnl commented on homework_3/api/client.py
> +                raise RequestErrorException(f'Request "{url}" failed with error "{error}"!')
И правда, как-то я не обратил внимания, когда смотрел код лекции

2020-10-26 22:21 UTC, snicks92 approved these changes

2020-10-26 22:21 UTC, merged